#include "Core/SGSLogChannels.h"

DEFINE_LOG_CATEGORY(LogSGS);
DEFINE_LOG_CATEGORY(LogSGSCard);
DEFINE_LOG_CATEGORY(LogSGSSkill);
DEFINE_LOG_CATEGORY(LogSGSTurn);
DEFINE_LOG_CATEGORY(LogSGSNet);
DEFINE_LOG_CATEGORY(LogSGSAI);
DEFINE_LOG_CATEGORY(LogSGSUI);
